apiVersion: apps/v1
kind: Deployment
metadata:
  name: accessgate-backend
  namespace: accessgate-poc
  labels:
    app: accessgate-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accessgate-backend
  template:
    metadata:
      labels:
        app: accessgate-backend
    spec:
      containers:
      - name: backend
        image: accessgate-backend:latest
        imagePullPolicy: Never  # Use local image for development
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: accessgate-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: accessgate-config
              key: PORT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: accessgate-config
              key: LOG_LEVEL
        - name: DATABASE_URL
          value: "postgresql://accessgate:$(POSTGRES_PASSWORD)@postgres-service:5432/accessgate"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: accessgate-secrets
              key: POSTGRES_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: accessgate-secrets
              key: JWT_SECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: accessgate-secrets
              key: JWT_REFRESH_SECRET
        - name: JWT_EXPIRES_IN
          valueFrom:
            secretKeyRef:
              name: accessgate-secrets
              key: JWT_EXPIRES_IN
        - name: JWT_REFRESH_EXPIRES_IN
          valueFrom:
            secretKeyRef:
              name: accessgate-secrets
              key: JWT_REFRESH_EXPIRES_IN
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: accessgate-config
              key: CORS_ORIGINS
        - name: RATE_LIMIT_WINDOW_MS
          valueFrom:
            configMapKeyRef:
              name: accessgate-config
              key: RATE_LIMIT_WINDOW_MS
        - name: RATE_LIMIT_MAX_REQUESTS
          valueFrom:
            configMapKeyRef:
              name: accessgate-config
              key: RATE_LIMIT_MAX_REQUESTS
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: accessgate-backend-service
  namespace: accessgate-poc
  labels:
    app: accessgate-backend
spec:
  selector:
    app: accessgate-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
